### ISSUE TITLE
Cache isn't being updated

### ISSUE THREAD

**Issue by LankyCyril** [torbiak/probe#13]
After I invoke probe for the first time in a project, it scans everything for a while and then is able to recall any of those files.

However, for example, after that I create a new file (include/chimerae.mk), make git track it, the whole shebang.

Even after I relaunch Vim, invoking :Probe and typing in "chim", I get nothing.

Ubuntu 12.04 (yeah...), Vim 7.3.

**Comment by campbellr** [comment]
I don't think probe ever invalidates its file cache unless explicitly told to ( @torbiak  can correct me if I'm wrong).

You can force a refresh with `:ProbeClearCache` or (or `C-r` if it hasn't been remapped).

**Comment by torbiak** [comment]
Yeah, that's how it works. Fuzzy file finders have been most useful for me on larger projects, where the directory hierarchies are deep and the time to scan them with vimscript is annoyingly long; I often want to take advantage of what's already cached rather than wait for a rescan. Also, if I'm changing files in a directory that probe has cached, I'm probably using Vim to change them and thus have buffers open for them: I'd use `:ProbeFindBuffer` to open new windows for them instead of rescanning and using `:ProbeFindFile`.

Since refreshing the cache manually is a part of normal probe operation, I'll update the docs to reflect that.

I believe other Vim fuzzy file finders, [command-t](https://github.com/wincent/command-t) and [ctrl-p](https://github.com/ctrlpvim/ctrlp.vim), behave similarly.
